{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
{{- range $key, $value := .Values.secret }}
{{- if ne $key "enabled" }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
{{- end }}
{{- end }}
